include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: true
    library_names: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    avoid_print: true
    avoid_void_async: true
    camel_case_extensions: true
    constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
